### ISSUE TITLE
Knowing all the pages you have stayed?

### ISSUE THREAD

**Issue by chiqui3d** [internetarchive/wayback#104]
Hey ,

As I can get all the text/html pages that have stayed?

Thanks

**Comment by kngenie** [comment]
I'm not sure I understand correctly, but if you're interested in enumerating all captures of a URL or domain, give CDX Server API a try: https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server (you cannot list _all_ the captures in the Wayback this way, though).

If you want to download all the HTML captures from Wayback Machine, there's no simple way to do it. You have to query for a list of captures with CDX Server API, and then download captures one by one. It'd be much faster to contact the web archive service organization for a copy of captures you're interested.
