### ISSUE TITLE
bugs.chromium.org reports an incorrect robots.txt restriction

### ISSUE THREAD

**Issue by nightpool** [internetarchive/wayback#140]
Navigate to: https://web.archive.org/web/http://bugs.chromium.org/p/project-zero/issues/detail?id=1139

see that wayback says it's blocked by robots.txt:

![image](https://cloud.githubusercontent.com/assets/233815/23288151/bda9fa56-fa0f-11e6-988e-2d893032e5ce.png)

See that the robots.txt for that domain, while complicated, [specifically allows that type of URL](https://bugs.chromium.org/robots.txt):

```
User-agent: *
# Start by disallowing everything.
Disallow: /
# Some specific things are okay, though.
Allow: /$
Allow: /hosting
Allow: /p/*/adminIntro
# Query strings are hard. We only allow ?id=N, no other parameters.
Allow: /p/*/issues/detail?id=*
Disallow: /p/*/issues/detail?id=*&*
Disallow: /p/*/issues/detail?*&id=*
# 10 second crawl delay for bots that honor it.
Crawl-delay: 10
```

Expect that complex robot.txt files are parsed and matched correctly by the wayback machine.

**Comment by nightpool** [comment]
web-beta seems to report a similar but distinct error. Not sure if this is related or not: https://web-beta.archive.org/web/20170224002517/https://bugs.chromium.org/p/project-zero/issues/detail?id=1139

![image](https://cloud.githubusercontent.com/assets/233815/23288249/6604ffc0-fa10-11e6-8ecf-066b1c377fac.png)

(I'm sure the page is archived, because it shows up under the search: https://web-beta.archive.org/web/*/https://bugs.chromium.org/p/project-zero/issues/detail?id=1139)

**Comment by kngenie** [comment]
Java Wayback's robots.txt parser doe's not understand wildcard and Allow: directives.
URL reported now plays back on web.archive.org (uses new robots.txt parser).
