### ISSUE TITLE
"404 Not Found" When trying to save reddit posts.

### ISSUE THREAD

**Issue by K4LCIFER** [internetarchive/wayback#245]
When trying to save any reddit post (take [this](https://www.reddit.com/r/murdermittens/comments/y27qdz/baby_apex_predator/), for example) the following page is displayed:
![image](https://user-images.githubusercontent.com/7829231/195478908-972ced78-5ade-4bf6-aac4-e6bf02048ecd.png)

**Comment by vbanos** [comment]
Thank you for your feedback. We have fixed this issue.
