### ISSUE TITLE
How can I get the result for https://web.archive.org/web/*/(keyword)  with api method?

### ISSUE THREAD

**Issue by yukeiyang** [internetarchive/wayback#269]
As I know, there is a way to search with url or domain within internet archive, same as `cdx api` does:
  
```
http://web.archive.org/cdx/search/cdx?url=archive.org
```

so, Is there a solution for search a keyword with api and not use url or domain method same as we do in archive.org website?
  
```
https://web.archive.org/web/*/(archive)
```

In the other word and furthermore, **how can I get the result for `https://web.archive.org/web/*/(archive)` with api in this case?**

**Comment by kruglyakovpawa83-dotcom** [comment]
[piev_46141343683630.pdf](https://github.com/user-attachments/files/21946597/piev_46141343683630.pdf)
[Халдекс 2.zip](https://github.com/user-attachments/files/21946590/2.zip)
[RecoveryKey.pdf](https://github.com/user-attachments/files/21946587/RecoveryKey.pdf)
[PFR_777000_0SZIE_20250513_8fe3ef7f-2f7e-11f0-ae93-9eca382dad1a.pdf](https://github.com/user-attachments/files/21946593/PFR_777000_0SZIE_20250513_8fe3ef7f-2f7e-11f0-ae93-9eca382dad1a.pdf)
[notificationService_2025-05-30.log](https://github.com/user-attachments/files/21946580/notificationService_2025-05-30.log)
[текст 2.txt](https://github.com/user-attachments/files/21946573/2.txt)
[новая папка 5.zip](https://github.com/user-attachments/files/21946576/5.zip)
[Халдекс 5 поколения.docx](https://github.com/user-attachments/files/21946575/5.docx)
[Экспортировано из Safari 2025-08-22.zip](https://github.com/user-attachments/files/21946596/Safari.2025-08-22.zip)
[WhatsApp-Logo.pdf](https://github.com/user-attachments/files/21946583/WhatsApp-Logo.pdf)
[logs 2.log](https://github.com/user-attachments/files/21946581/logs.2.log)
[dialer_2025-06-10.log](https://github.com/user-attachments/files/21946600/dialer_2025-06-10.log)
[Детализация_250058642103_20250728.pdf](https://github.com/user-attachments/files/21946601/_250058642103_20250728.pdf)
[Халдекс 6 поколения.docx](https://github.com/user-attachments/files/21946608/6.docx)
[WhatsApp-Logo.zip](https://github.com/user-attachments/files/21946574/WhatsApp-Logo.zip)

[Детализация_250058642103_20250728 — со сжатием.pdf](https://github.com/user-attachments/files/21946578/_250058642103_20250728.pdf)
[68994bafe7a2d_logs 2.zip](https://github.com/user-attachments/files/21946606/68994bafe7a2d_logs.2.zip)
[Халдекс.zip](https://github.com/user-attachments/files/21946594/default.zip)
<img width="82" height="82" alt="Image" src="https://github.com/user-attachments/assets/926848ad-12ea-4cea-b959-8fbc4103c110" />
[Ааа.zip](https://github.com/user-attachments/files/21946589/default.zip)

[Халдекс 4 поколения.docx](https://github.com/user-attachments/files/21946585/4.docx)

[68994bafe7a2d_logs.zip](https://github.com/user-attachments/files/21946602/68994bafe7a2d_logs.zip)
[новая папка.zip](https://github.com/user-attachments/files/21946586/default.zip)
[новая папка 4.zip](https://github.com/user-attachments/files/21946582/4.zip)
[новая папка 2.zip](https://github.com/user-attachments/files/21946609/2.zip)
![Image](https://github.com/user-attachments/assets/b96c7150-db82-42c9-8163-70e7d3903f74)
[текст.txt](https://github.com/user-attachments/files/21946588/default.txt)
[RecoveryKey.pdf](https://github.com/user-attachments/files/21946599/RecoveryKey.pdf)
[Халдекс 2.zip](https://github.com/user-attachments/files/21946598/2.zip)
[Халдекс 5 поколения.docx](https://github.com/user-attachments/files/21946577/5.docx)
[Экспортировано из Safari 2025-08-22.zip](https://github.com/user-attachments/files/21946592/Safari.2025-08-22.zip)
[logs 2.log](https://github.com/user-attachments/files/21946584/logs.2.log)
[Халдекс.zip](https://github.com/user-attachments/files/21946595/default.zip)
[Халдекс 6 поколения.docx](https://github.com/user-attachments/files/21946604/6.docx)
[68994bafe7a2d_logs.zip](https://github.com/user-attachments/files/21946591/68994bafe7a2d_logs.zip)
[новая папка 3.zip](https://github.com/user-attachments/files/21946603/3.zip)
[Халдекс 2.zip](https://github.com/user-attachments/files/21946607/2.zip)
[logs 2.log](https://github.com/user-attachments/files/21946605/logs.2.log)
[Халдекс 2.zip](https://github.com/user-attachments/files/21946579/2.zip)
