### ISSUE TITLE
gapless playback on archive.org

### ISSUE THREAD

**Issue by whit537** [internetarchive/wayback#96]
I'm listening to [the Dead on archive.org](https://archive.org/details/gd89-04-11.sbd.miller.15109.sbeok.shnf), and it would sher be swell to have gapless playback, to reduce the buzzkill when listening to Dead concerts (I'm currently working through 1989 :).

This is almost certainly the wrong repo for this ticket. Can you point me to the right repo?

I looked at the banner and "Help," "Jobs," and "Volunteer" all sound the same to me, and none of them answered the "which repo" question for me.

![screen shot 2015-08-27 at 10 52 03 pm](https://cloud.githubusercontent.com/assets/134455/9538064/4ae5996c-4d0e-11e5-914a-ea60bf6f1e51.png)

The closest was https://developers.archive.org/get-started/. That seems to be aimed more at developers using JSON APIs than developers interested in helping with the software itself.

I also browsed around https://github.com/internetarchive ... and even ended up on https://github.com/iipc (:scream_cat: good lord what is this!?). I found a repo for Wayback, but I think that's different than what I want, right? Is there a repo for archive.org?

Thanks! :-)

**Comment by dmolesUC3** [comment]
It looks like the IA audio archive uses [JW Player](http://www.jwplayer.com/), so you might want to talk to them. Or try the [Live Music Archive Forum](https://archive.org/details/etree&tab=forum).

**Comment by whit537** [comment]
Thanks @dmolesUC3! :-)
